package pgdialect

import (
	"strings"

	"github.com/piprim/pgcrud/dialect"
	"github.com/piprim/pgcrud/dialect/feature"
	"github.com/piprim/pgcrud/dialect/sqltype"
	"github.com/piprim/pgcrud/schema"
)

var pgDialect = New()

type Dialect struct {
	tables    *schema.Tables
	features  feature.Feature
	uintAsInt bool
}

var _ schema.Dialect = (*Dialect)(nil)

func New(opts ...DialectOption) *Dialect {
	d := new(Dialect)
	d.tables = schema.NewTables(d)
	d.features = feature.CTE |
		feature.WithValues |
		feature.Returning |
		feature.InsertReturning |
		feature.DefaultPlaceholder |
		feature.DoubleColonCast |
		feature.InsertTableAlias |
		feature.UpdateTableAlias |
		feature.DeleteTableAlias |
		feature.TableCascade |
		feature.TableIdentity |
		feature.TableTruncate |
		feature.TableNotExists |
		feature.InsertOnConflict |
		feature.SelectExists |
		feature.GeneratedIdentity |
		feature.CompositeIn |
		feature.FKDefaultOnAction |
		feature.DeleteReturning |
		feature.Merge |
		feature.MergeReturning |
		feature.AlterColumnExists |
		feature.CreateIndexIfNotExists

	for _, opt := range opts {
		opt(d)
	}

	return d
}

type DialectOption func(d *Dialect)

func WithoutFeature(other feature.Feature) DialectOption {
	return func(d *Dialect) {
		d.features = d.features.Remove(other)
	}
}

func WithAppendUintAsInt(on bool) DialectOption {
	return func(d *Dialect) {
		d.uintAsInt = on
	}
}

func (d *Dialect) Name() dialect.Name {
	return dialect.PG
}

func (d *Dialect) Features() feature.Feature {
	return d.features
}

func (d *Dialect) Tables() *schema.Tables {
	return d.tables
}

func (d *Dialect) OnTable(table *schema.Table) {
	for _, field := range table.FieldMap {
		d.onField(field)
	}
}

func (d *Dialect) onField(field *schema.Field) {
	field.DiscoveredSQLType = fieldSQLType(field)

	if field.AutoIncrement && !field.Identity {
		switch field.DiscoveredSQLType {
		case sqltype.SmallInt:
			field.CreateTableSQLType = pgTypeSmallSerial
		case sqltype.Integer:
			field.CreateTableSQLType = pgTypeSerial
		case sqltype.BigInt:
			field.CreateTableSQLType = pgTypeBigSerial
		}
	}

	if field.Tag.HasOption("array") || strings.HasSuffix(field.UserSQLType, "[]") {
		field.Append = d.arrayAppender(field.StructField.Type)
		field.Scan = arrayScanner(field.StructField.Type)
		return
	}

	if field.Tag.HasOption("multirange") || strings.HasSuffix(field.UserSQLType, "multirange") {
		field.Scan = arrayScanner(field.StructField.Type)
		return
	}

	switch field.DiscoveredSQLType {
	case sqltype.HSTORE:
		field.Append = d.hstoreAppender(field.StructField.Type)
		field.Scan = hstoreScanner(field.StructField.Type)
	}
}

func (d *Dialect) IdentQuote() byte {
	return '"'
}

// UintAsInt reports whether WithAppendUintAsInt is on: unsigned values are
// bound as the signed type of the same width, wrapping on overflow.
func (d *Dialect) UintAsInt() bool {
	return d.uintAsInt
}

func (d *Dialect) AppendSequence(b []byte, _ *schema.Table, _ *schema.Field) []byte {
	return appendGeneratedAsIdentity(b)
}

// appendGeneratedAsIdentity appends GENERATED BY DEFAULT AS IDENTITY to the column definition.
func appendGeneratedAsIdentity(b []byte) []byte {
	return append(b, " GENERATED BY DEFAULT AS IDENTITY"...)
}
